"""HTML and JSON report generation."""

from __future__ import annotations

import json
from html import escape
from pathlib import Path

from app.core.models import InventorySnapshot
from app.core.safety import validate_output_write


def write_reports(snapshot: InventorySnapshot) -> dict[str, str]:
    output = validate_output_write(Path(snapshot.output_folder))
    paths = {
        "Inventory.json": str(output / "Inventory.json"),
        "ProductionMap.html": str(output / "ProductionMap.html"),
        "FolderMap.html": str(output / "FolderMap.html"),
        "ScheduledTasks.html": str(output / "ScheduledTasks.html"),
        "DuplicateFiles.html": str(output / "DuplicateFiles.html"),
        "Recommendations.html": str(output / "Recommendations.html"),
    }

    (output / "Inventory.json").write_text(
        json.dumps(snapshot.to_dict(), indent=2),
        encoding="utf-8",
    )
    paths["ProductionMap.html"] = _write_html(
        output / "ProductionMap.html",
        "Production Map",
        _production_map_body(snapshot),
    )
    paths["FolderMap.html"] = _write_html(
        output / "FolderMap.html",
        "Folder Map",
        _folder_map_body(snapshot),
    )
    paths["ScheduledTasks.html"] = _write_html(
        output / "ScheduledTasks.html",
        "Scheduled Tasks",
        _tasks_body(snapshot),
    )
    paths["DuplicateFiles.html"] = _write_html(
        output / "DuplicateFiles.html",
        "Duplicate Files",
        _duplicates_body(snapshot),
    )
    paths["Recommendations.html"] = _write_html(
        output / "Recommendations.html",
        "Recommendations",
        _recommendations_body(snapshot),
    )
    return paths


def _write_html(path: Path, title: str, body: str) -> str:
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{escape(title)}</title>
  <style>
    body {{ font-family: Segoe UI, Arial, sans-serif; margin: 24px; color: #1f2933; }}
    h1, h2 {{ color: #0f4c81; }}
    table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
    th, td {{ border: 1px solid #d9e2ec; padding: 8px; text-align: left; vertical-align: top; }}
    th {{ background: #f0f4f8; }}
    .muted {{ color: #627d98; }}
    .badge {{ display: inline-block; padding: 2px 8px; border-radius: 10px; background: #d9e2ec; }}
  </style>
</head>
<body>
  <h1>{escape(title)}</h1>
  <p class="muted">Generated by Mo's Place Inventory · Read-only scan</p>
  {body}
</body>
</html>"""
    path.write_text(html, encoding="utf-8")
    return str(path)


def _production_map_body(snapshot: InventorySnapshot) -> str:
    rows = "".join(
        f"<tr><td>{escape(hit.name)}</td><td>{escape(hit.computer)}</td><td>{escape(hit.kind)}</td><td>{escape(hit.path)}</td></tr>"
        for hit in snapshot.components
    )
    return f"""
    <h2>Radio Components</h2>
    <table><tr><th>Component</th><th>Computer</th><th>Kind</th><th>Path</th></tr>{rows or '<tr><td colspan=4>No components found</td></tr>'}</table>
    <h2>Drives</h2>
    <table><tr><th>Computer</th><th>Drive</th><th>Total</th><th>Free</th></tr>
    {''.join(f'<tr><td>{escape(d.computer)}</td><td>{escape(d.letter)}</td><td>{d.total_bytes:,}</td><td>{d.free_bytes:,}</td></tr>' for d in snapshot.drives)}
    </table>
    """


def _folder_map_body(snapshot: InventorySnapshot) -> str:
    rows = "".join(
        f"<tr><td>{escape(row.relative_path)}</td><td>{escape(row.office_status)}</td><td>{escape(row.radio_status)}</td><td>{escape(row.platform_status)}</td><td>{escape(row.detail)}</td></tr>"
        for row in snapshot.comparisons[:2000]
    )
    folder_rows = "".join(
        f"<tr><td>{escape(folder.computer)}</td><td>{escape(folder.path)}</td><td>{folder.file_count}</td><td>{folder.total_size:,}</td></tr>"
        for folder in snapshot.folders[:2000]
    )
    return f"""
    <h2>Folder Comparison</h2>
    <table><tr><th>Relative Path</th><th>Office</th><th>Radio</th><th>Platform</th><th>Detail</th></tr>{rows}</table>
    <h2>Folder Inventory</h2>
    <table><tr><th>Computer</th><th>Folder</th><th>Files</th><th>Total Size</th></tr>{folder_rows}</table>
    """


def _tasks_body(snapshot: InventorySnapshot) -> str:
    rows = "".join(
        f"<tr><td>{escape(task.computer)}</td><td>{escape(task.name)}</td><td>{escape(task.program)}</td><td>{escape(task.working_directory)}</td><td>{escape(task.status)}</td><td>{escape(task.trigger)}</td></tr>"
        for task in snapshot.tasks
    )
    process_rows = "".join(
        f"<tr><td>{escape(proc.computer)}</td><td>{escape(proc.name)}</td><td>{escape(proc.executable)}</td><td>{escape(proc.command_line)}</td></tr>"
        for proc in snapshot.processes[:1000]
    )
    service_rows = "".join(
        f"<tr><td>{escape(svc.computer)}</td><td>{escape(svc.name)}</td><td>{escape(svc.status)}</td><td>{escape(svc.startup_type)}</td><td>{escape(svc.executable)}</td></tr>"
        for svc in snapshot.services[:1000]
    )
    return f"""
    <h2>Scheduled Tasks</h2>
    <table><tr><th>Computer</th><th>Task</th><th>Program</th><th>Working Directory</th><th>Status</th><th>Trigger</th></tr>{rows}</table>
    <h2>Running Processes</h2>
    <table><tr><th>Computer</th><th>Process</th><th>Executable</th><th>Command Line</th></tr>{process_rows}</table>
    <h2>Windows Services</h2>
    <table><tr><th>Computer</th><th>Name</th><th>Status</th><th>Startup</th><th>Executable</th></tr>{service_rows}</table>
    """


def _duplicates_body(snapshot: InventorySnapshot) -> str:
    rows = "".join(
        f"<tr><td>{escape(group.kind)}</td><td>{escape(group.key)}</td><td>{'<br>'.join(escape(p) for p in group.paths)}</td></tr>"
        for group in snapshot.duplicates[:2000]
    )
    return f"<table><tr><th>Type</th><th>Key</th><th>Paths</th></tr>{rows or '<tr><td colspan=3>No duplicates found</td></tr>'}</table>"


def _recommendations_body(snapshot: InventorySnapshot) -> str:
    rows = "".join(
        f"<tr><td>{escape(rec.category)}</td><td><span class='badge'>{escape(rec.severity)}</span></td><td>{escape(rec.title)}</td><td>{escape(rec.detail)}</td><td>{'<br>'.join(escape(p) for p in rec.paths)}</td></tr>"
        for rec in snapshot.recommendations
    )
    return f"<table><tr><th>Category</th><th>Severity</th><th>Title</th><th>Detail</th><th>Paths</th></tr>{rows or '<tr><td colspan=5>No recommendations</td></tr>'}</table>"
